import {
  to = module.github_repository["estate-config"].github_repository.github_repository
  id = "estate-config"
}

import {
  to = module.github_repository["tofu-modules"].github_repository.github_repository
  id = "tofu-modules"
}

import {
  to = module.github_repository["planzoco"].github_repository.github_repository
  id = "planzoco"
}

import {
  to = module.github_repository["estate-repos"].github_repository.github_repository
  id = "estate-repos"
}
