name: apply_tofu

on:
  push:
    paths:
      - "tofu/**"
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write

env:
  TF_VAR_org_name: ${{ github.repository_owner }}
  TF_VAR_repo_name: ${{ github.event.repository.name }}
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  GITHUB_APP_ID: ${{ secrets.EVOTEUMBOT_APP_ID }}
  GITHUB_APP_INSTALLATION_ID: ${{ secrets.EVOTEUMBOT_APP_INSTALLATION_ID }}
  GITHUB_APP_PEM_FILE: ${{ secrets.EVOTEUMBOT_APP_PEM_FILE }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.9.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: ${{ github.event.repository.name }}--${{ github.workflow }}--${{ github.run_number }}--${{ github.job }}

    - name: Verify AWS Authentication
      run: |
        aws sts get-caller-identity >/dev/null && echo "✓ AWS accessible" || echo "✗ AWS not accessible"

    - name: Ensure state file exists
      run: |
        echo "Checking for existing state file"
        if ! aws s3api head-object --bucket ${{ secrets.TOFU_STATE_BUCKET_NAME }} --key ${{ github.event.repository.name }}/tofu.tfstate 2>/dev/null; then
          echo "No state file found, creating empty state"
          echo "{}" | aws s3 cp - s3://${{ secrets.TOFU_STATE_BUCKET_NAME }}/${{ github.event.repository.name }}/tofu.tfstate
        else
          echo "✓ State file exists"
        fi

    - name: Do that OpenTofu that you do so well
      id: plan
      run: |
        cd tofu
        echo "Verifying S3 bucket access"
        aws s3 ls s3://${{ secrets.TOFU_STATE_BUCKET_NAME }} >/dev/null && echo "✓ S3 bucket accessible" || (echo "✗ S3 bucket not accessible" && exit 1)
        echo "Initializing OpenTofu"
        tofu init -input=false \
          -backend-config="bucket=${{ secrets.TOFU_STATE_BUCKET_NAME }}" \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="key=${{ github.event.repository.name }}/tofu.tfstate"
        echo "Planning OpenTofu"
        tofu plan -input=false -out=tfplan | tee plan.txt
        echo "Showing OpenTofu plan"
        tofu show -json tfplan > tfplan.json
        if grep -q "No changes." plan.txt; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Apply OpenTofu configuration
      if: steps.plan.outputs.changes == 'true'
      run: |
        cd tofu
        echo "Applying OpenTofu configuration"
        tofu apply tfplan
        