name: tofu_state_check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

env:
  GITHUB_APP_ID: ${{ secrets.EVOTEUMBOT_APP_ID }}
  GITHUB_APP_INSTALLATION_ID: ${{ secrets.EVOTEUMBOT_APP_INSTALLATION_ID }}
  GITHUB_APP_PEM_FILE: ${{ secrets.EVOTEUMBOT_APP_PEM_FILE }}
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  TF_VAR_org_name: ${{ github.repository_owner }}
  TF_VAR_repo_name: ${{ github.event.repository.name }}
  TF_VAR_repo_url: ${{ github.event.repository.html_url }}

jobs:
  check-state:
    name: Check OpenTofu State
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: set additional env vars
        run: |
          export ENVIRONMENT=development
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "TF_VAR_environment=$ENVIRONMENT" >> $GITHUB_ENV
          echo "STATE_FILE_KEY=${{ github.event.repository.name }}/$ENVIRONMENT/tofu.tfstate" >> $GITHUB_ENV


      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.event.repository.name }}--${{ github.workflow }}--${{ github.run_number }}--${{ github.job }}

      - name: initialise tofu
        run: |
            echo "===== Processing Environment: ${{ github.event.repository.name }}/$ENVIRONMENT ====="
            cd tofu/development
            echo "Running tofu init for environment: $ENVIRONMENT"
            tofu init \
              -input=false \
              -backend-config="bucket=${{ secrets.TOFU_STATE_BUCKET_NAME }}" \
              -backend-config="key=$STATE_FILE_KEY" \
              -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Show OpenTofu State List
        run: tofu state list