name: tofu-apply-all-environments

on:
  workflow_dispatch:
  push:
    paths:
      - "tofu/**"
      - repos.yml

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  deploy-multi-tofu:
    uses: evoteum/estate-reusable-workflows/.github/workflows/tofu-apply-all-environments.yml@main
    secrets: inherit
    with:
      fail_fast: false
      environments: development
