name: tofu-apply

on:
  workflow_dispatch:
  push:
    paths:
      - "tofu/**"
      - repos.yml
  schedule:
    - cron: "0 23 * * *"  # Every day at 11 PM

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  deploy-multi-tofu:
    uses: evoteum/estate-reusable-workflows/.github/workflows/tofu-apply.yml@main
    secrets: inherit
    with:
      fail_fast: false
      environments: development
